### ISSUE TITLE
[Repertory-List] : Erro Paginator

### ISSUE THREAD

**Issue by jobdev-hub** [acervomusical/webapp#119]
**COMO SIMULAR ERRO:**
--> Manter 6 repertórios cadastrados
--> Tentar acessar PAGE 2

![erro-paginator-nao-esta-habilitando-navegacao-proximas-paginas](https://user-images.githubusercontent.com/57804223/122099665-a89e8580-cde8-11eb-930b-86b34c26ef3b.PNG)

**Comment by marcospaulo-paixao** [comment]
Ajustado conforme solicitado

**Comment by jobdev-hub** [comment]
aprovado!
