### ISSUE TITLE
[Login] Alterar import do environment

### ISSUE THREAD

**Issue by jobdev-hub** [acervomusical/webapp#125]
Alterar importação para environment.prod para visualizar atributo 'version'

![image](https://user-images.githubusercontent.com/57804223/122409938-e969dc00-cf59-11eb-99b2-1c4ae44394ee.png)

**Comment by Viniciusalopes** [comment]
Na verdade, basta acrescentar o atributo version na environment, conforme imagem abaixo.

![image](https://user-images.githubusercontent.com/33704906/122473221-ef7ead80-cf97-11eb-9adb-ee015627e691.png)

**Comment by marcospaulo-paixao** [comment]
Qual o motivo?

**Comment by Viniciusalopes** [comment]
Criei esse atributo '`version`' para colocar a informação de numero da versão fora do componente de login, e evitar o uso de `CRTL+F` para saber onde a informação é exibida.para ser utilizada.
Com o atributo no environment, a informação de versão pode ser reutilizada em outros componentes e, a cada nova versão, a atualização do númer é feita em um lugar só.

**Comment by marcospaulo-paixao** [comment]
Agora que fez sentido.

**Comment by Viniciusalopes** [comment]
> Agora que fez sentido.

![image](https://user-images.githubusercontent.com/33704906/122474603-d971ec80-cf99-11eb-983f-a3bc1924a68e.png)

**Comment by Viniciusalopes** [comment]
O arquivo `environment.ts` não está mais subindo pro git (ou pelo menos não deveria)
A solução neste caso é alterar o arquivo local, acrescentando o atributo version na environment, conforme imagem abaixo.
> 
> ![image](https://user-images.githubusercontent.com/33704906/122473221-ef7ead80-cf97-11eb-9adb-ee015627e691.png)

**Comment by marcospaulo-paixao** [comment]
Ajustado conforme solicitado. [correção issues 125 #136](https://github.com/acervomusical/webapp/pull/136/commits/a769eab302d87c8863a0f4643291a9f43c25d80c)
![image](https://user-images.githubusercontent.com/55635755/122481041-5f933080-cfa4-11eb-86c3-0a3ab31031cd.png)
