### ISSUE TITLE
[Repertory] Erro para criar novos repertórios

### ISSUE THREAD

**Issue by jobdev-hub** [acervomusical/webapp#133]
![image](https://user-images.githubusercontent.com/57804223/122425272-bfb6b200-cf65-11eb-974f-826ef578d668.png)

**Comment by jobdev-hub** [comment]
Error Translate:

"trace": "org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientObjectException: o objeto faz referência a uma instância transitória não salva - salve a instância transitória antes de limpar: br.mus.acervo.backend.model.Orchestration; a exceção aninhada é java. lang.IllegalStateException: org.hibernate.TransientObjectException: o objeto faz referência a uma instância transitória não salva - salve a instância transitória antes de liberar: br.mus.acervo.backend.model.Orchestration \ r \ n \ tat

**Comment by Viniciusalopes** [comment]
Resolvido:
https://github.com/acervomusical/backend/commit/2fcedf0fbd58144dd35ed99e7a51c3623028a7bb
