### ISSUE TITLE
[music-list] Dialog Confirmação Delete não implementado

### ISSUE THREAD

**Issue by lucasDEV20** [acervomusical/webapp#151]
https://user-images.githubusercontent.com/55209015/122817131-f0705180-d2ad-11eb-80e5-7a678c60d3b3.mp4

**Comment by jobdev-hub** [comment]
Isso não é dialog de confirmação de delete não implementado.
trata-se de outro erro referente a o não tratamento da mensagem de exceção.
provavlemente será no backEnd e não aqui no frontEnd.

**Comment by jobdev-hub** [comment]
improcedente!
Iremos reavaliar esse levantamento, por hora pode encerrar a demanda.
