### ISSUE TITLE
[mediatype-list] ] Dialog Confirmação Delete não implementado

### ISSUE THREAD

**Issue by lucasDEV20** [acervomusical/webapp#152]
https://user-images.githubusercontent.com/55209015/122818613-d0da2880-d2af-11eb-93cb-b7a2722f411d.mp4

**Comment by jobdev-hub** [comment]
Isso não dialog de confirmação de delete não implementado.
trata-se de outro erro referente a o não tratamento da mensagem de exceção.
provavlemente será no backEnd e não aqui no frontEnd.

**Comment by jobdev-hub** [comment]
improcedente!
Iremos reavaliar esse levantamento, por hora pode encerrar a demanda.
