### ISSUE TITLE
[music-form]  ] Dialog Confirmação Delete não implementado (Autores)

### ISSUE THREAD

**Issue by lucasDEV20** [acervomusical/webapp#153]
https://user-images.githubusercontent.com/55209015/122819023-434b0880-d2b0-11eb-9bb3-d83e685ed841.mp4

**Comment by jobdev-hub** [comment]
isso não é no musci-form, favor revisar.
Isso é em um list chamado pelo music-form.
Favor verificar o nome correto

**Comment by jobdev-hub** [comment]
improcedente!
Iremos reavaliar esse levantamento, por hora pode encerrar a demanda.
