### ISSUE TITLE
[music-form} ] Dialog Confirmação Delete não implementado [orquestraçao]

### ISSUE THREAD

**Issue by lucasDEV20** [acervomusical/webapp#154]
https://user-images.githubusercontent.com/55209015/122819318-ac328080-d2b0-11eb-849c-7ac73df1ef7f.mp4

**Comment by jobdev-hub** [comment]
isso não é no musci-form, favor revisar.
Isso é em um list chamado pelo music-form.
Favor verificar o nome correto

**Comment by jobdev-hub** [comment]
improcedente!
Iremos reavaliar esse levantamento, por hora pode encerrar a demanda.
