### ISSUE TITLE
[ arranger ] Dialog Confirmação Delete não implementado

### ISSUE THREAD

**Issue by lucasDEV20** [acervomusical/webapp#155]
https://user-images.githubusercontent.com/55209015/122819547-00d5fb80-d2b1-11eb-83ef-3a6b33f4a615.mp4

**Comment by jobdev-hub** [comment]
isso não é no musci-form, favor revisar.
Isso é em um dialog chamado pelo music-form.
Favor verificar o nome correto

**Comment by jobdev-hub** [comment]
improcedente!
Iremos reavaliar esse levantamento, por hora pode encerrar a demanda.
