### ISSUE TITLE
[part]  Dialog Confirmação Delete não implementado 

### ISSUE THREAD

**Issue by lucasDEV20** [acervomusical/webapp#156]
https://user-images.githubusercontent.com/55209015/122819822-4f839580-d2b1-11eb-8cb8-b9b670672e48.mp4

**Comment by jobdev-hub** [comment]
isso não é no musci-form, favor revisar.
Isso é em um dialog chamado pelo music-form.
Favor verificar o nome correto

**Comment by jobdev-hub** [comment]
improcedente!
Iremos reavaliar esse levantamento, por hora pode encerrar a demanda.
