### ISSUE TITLE
Login - Requisição sem email e senha

### ISSUE THREAD

**Issue by Viniciusalopes** [acervomusical/webapp#35]
1. Não fazer a requisição de login se os dois campos não estiverem preenchidos,  
ou então tratar a informação, retornando instruções mais específicas sobre cada campo. 
As mensagens de retorno podem ser as mesmas que aparecem em vermelho, no formulário. 

2. Trocar a palavra **forneça** por **informe**

![image](https://user-images.githubusercontent.com/33704906/117578929-245d3200-b0c7-11eb-901a-539870703cbc.png)

**Comment by marcospaulo-paixao** [comment]
Ajustado conforme solicitado! Favor validar.
![image](https://user-images.githubusercontent.com/55635755/118909936-1fd01f00-b8fa-11eb-8760-11a1c3ae55a8.png)
![image](https://user-images.githubusercontent.com/55635755/118909988-35454900-b8fa-11eb-90c2-e8fca15f4666.png)

**Comment by Viniciusalopes** [comment]
Resolvido.
