### ISSUE TITLE
Forgot-password: Requisição sem e-mail

### ISSUE THREAD

**Issue by Viniciusalopes** [acervomusical/webapp#36]
1. Tornar o campo e-mail obrigatório no formulário.

2. Não fazer a requisição de nova senha sem informar o e-mail,
ou então tratar a informação, retornando instruções mais específicas e informando que o e-mail é obrigatório.

![image](https://user-images.githubusercontent.com/33704906/117579705-76538700-b0ca-11eb-81c6-9c79952fe953.png)

**Comment by marcospaulo-paixao** [comment]
Ajustado conforme solicitado! Favor validar.
![image](https://user-images.githubusercontent.com/55635755/118910160-658ce780-b8fa-11eb-9ca0-5f54bc04b3f7.png)

**Comment by Viniciusalopes** [comment]
Resolvido.
